github:
  org: "wendxy"
  includeRepos: []
  excludeRepos: []
  mainBranchDefault: "main"

authors:
  emails:
    - "ngangiang.le92@gmail.com"
  usernames:
    - "wendxy"

notion:
  databaseId: "318b6fad96858035bc53d1243b8a9171"

whatsapp:
  recipient: "61431352142"
  templateName: "daily_code_summary"
  languageCode: "en"

openai:
  model: "gpt-4.1-mini"
  maxTokens: 1200
